<a href="https://colab.research.google.com/github/ChojnackiKRZ/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__
#print (dir(np))

**1.MACIERZE PODSTAWY**

1d array

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])

In [ ]:
type (x)

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y = np.array([1.3, 2.4, 4.1])

In [ ]:
y.dtype

dtype('float64')

2d array

In [ ]:
z = np.array([[1, -3], [2, 6]])

In [ ]:
z.ndim

2

In [ ]:
z.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 4],[3, 2, 1]])

In [ ]:
x.shape

(2, 3)

3d array

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [2, 5, 1]],
     [[4, 3, 1],
      [4, 2, 1]],
     [[5, 6, 4],
      [9, 8, 2]]]
)

In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)

**2.PODSTAWOWE TYPY DANYCH**

In [ ]:
a = np.array([1.9, 2, 3])
a.dtype

dtype('float64')

In [ ]:
a = np.array([1, 2, 3], dtype= 'float')
a

array([1., 2., 3.])

In [ ]:
a = np.array([False, True])
a
a.dtype

dtype('bool')

In [ ]:
#specjalne typy numpy
a = np.array([1, 28, 257], dtype = np.int8)
b = np.array([1, 28, 255], dtype = np.int8)
c = np.array([1, 28, 256], dtype = np.int8)
print (a, b, c)

[ 1 28  1] [ 1 28 -1] [ 1 28  0]


**3.TWORZENIE TABLIC**

In [ ]:
#help (np.zeros)
np.zeros((4,10))

In [ ]:
np.zeros((4,10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones((5,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape = (3, 3), fill_value= 5, dtype = int)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
a = np.arange(1, 6, 2)
b = np.arange(1, 6, 2)
c = a + b
print (c)

[ 2  6 10]


In [ ]:
np.arange(100, 49, -10)

array([100,  90,  80,  70,  60,  50])

In [ ]:
np.arange(0, 1, step = 0.01)

In [ ]:
for i in np.linspace(start = 0, stop = 1, num = 10):
  print (round (i, 1))

In [ ]:
A = np.arange(15)

In [ ]:
print (A)
A.reshape(5, 3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
#jeżeli nie chcesz liczyć, jaki ma być wymiar, podajesz jako pierwszy lub 
#drugi parametr -1
A = np.arange(20)
B = np.arange(15)
print (A.reshape(4, -1))
print (B.reshape(-1, 3))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


**4.PODSTAWOWE OPERACJE NA MACIERZACH**

In [ ]:
A = np.array([[3, 1, 5, 6], [2, 8, 9, 10]])
B = np.array([2, -8, 9, 1])

A + B
A * B
A / B

In [ ]:
#przez stałą
A + 3
A * 3
A / 3

In [ ]:
#Metody dla macierzy - numpy
#1.Dodawanie
np.add(A, B)

array([[ 5, -7, 14,  7],
       [ 4,  0, 18, 11]])

In [ ]:
#2.Odejmowanie
np.subtract(A, B)

array([[ 1,  9, -4,  5],
       [ 0, 16,  0,  9]])

In [ ]:
#3.Mnożenie
np.multiply(A, B)

array([[  6,  -8,  45,   6],
       [  4, -64,  81,  10]])

In [ ]:
#4.Dzielenie
np.divide(A, B)

array([[ 1.5       , -0.125     ,  0.55555556,  6.        ],
       [ 1.        , -1.        ,  1.        , 10.        ]])

**4.1.MNOŻENIE MACIERZY**

In [ ]:
x = np.array([[2, 3],[5, 3]])
y = np.array([[-5, 2],[9, -2]])

In [ ]:
print (x, '\n')
print (y)


In [ ]:
x * y

array([[-10,   6],
       [ 45,  -6]])

In [ ]:
#wiersz * kolumna, wiersz * kolumna
np.dot(x, y)

array([[17, -2],
       [ 2,  4]])

In [ ]:
#mnożenie macierzy nie jest przemienne
print (np.dot(x, y), '\n')
print (np.dot(y, x))

[[17 -2]
 [ 2  4]] 

[[ 0 -9]
 [ 8 21]]


In [ ]:
#można zastosować symbol '@'
print (x @ y, '\n')
print (y @ x)

[[17 -2]
 [ 2  4]] 

[[ 0 -9]
 [ 8 21]]


**5.GENEROWANIE LICZB PSEUDOLOSOWYCH**

a) rozkład normalny

In [ ]:
np.random.seed(0)
np.random.randn(10, 4) #pierwszy parametr: liczba wierszy, drugi: liczba kolumn

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275]])

b) rozkład jednostajny na przedziale

In [ ]:
#funkcja rand zwróci nam liczby z przedziału 0 - 1
np.random.rand(10, 3)

array([[0.83794491, 0.09609841, 0.97645947],
       [0.4686512 , 0.97676109, 0.60484552],
       [0.73926358, 0.03918779, 0.28280696],
       [0.12019656, 0.2961402 , 0.11872772],
       [0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949],
       [0.52324805, 0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895, 0.66741038],
       [0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755]])

c) randint: 


      1) liczbę, gdzie podany parametr jest sufitem, a min to 0

In [ ]:
np.random.randint(10)

0

          2) liczbę z zakresu

In [ ]:
np.random.randint(4, 10)

4

        3) macierz losowych liczb

In [ ]:
np.random.randint(1, 15, 6)

array([ 1,  5,  4, 14, 12, 13])

d) choice: losowy wybór z obiektu

In [ ]:
a = [6, 4, 2, 6]
a2 = np.array([[6, 4, 2, 6],[5, 2, 8, 9]])
np.random.choice(a2[0])

6

**TASOWANIE DANYCH W MACIERZY**

In [ ]:
a = np.arange(2, 10)
a = a.reshape(2, 4)
np.random.shuffle(a)
a

array([[6, 7, 8, 9],
       [2, 3, 4, 5]])

**6.PODSTAWOWE FUNKCJE W BIBLIOTECE NUMPY**

In [196]:
np.exp(1)

2.718281828459045

In [197]:
np.sqrt(3)

1.7320508075688772

In [201]:
np.all([2, 1, 0])

False

In [205]:
print (np.any([2, 1, 9, 9]))
print (np.any([0, 1, 1, 1]))
print (np.any([0, 0, 0, 0]))

True
True
False


In [211]:
A = np.random.rand(5)
A
#zwracamy indeks największej liczby w macierzy
print (A)
print (np.argmax(A))
A[np.argmax(A)]

[0.1494483  0.86812606 0.16249293 0.61555956 0.12381998]
1


0.8681260573682142

In [212]:
A = np.random.rand(5)
A
#zwracamy indeks najmniejszej liczby w macierzy
print (A)
print (np.argmin(A))
A[np.argmin(A)]

[0.84800823 0.80731896 0.56910074 0.4071833  0.069167  ]
4


0.06916699545513805

In [215]:
#tutaj zwracamy w postaci indeksów kolejność wyników w macierzy od najmniejszego
#do największego
A = np.random.rand(5)
print (A)
np.argsort(A)

[0.85580334 0.01171408 0.35997806 0.72999056 0.17162968]


array([1, 4, 2, 3, 0])

In [216]:
np.max(A)

0.855803342392611

In [217]:
np.mean(A)

0.4258231461482951

In [218]:
np.median(A)

0.3599780644783639

In [219]:
np.std(A)

0.32181889189143154

**7.INDEKSOWANIE/WYCINANIE**

In [230]:
A = np.arange(20)
A
print (A[5])
print (A[5:8])
print (A[:5])
print (A[5:])
print (A[-1])
print (A[:-1])

5
[5 6 7]
[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
19
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [240]:
#wycinanie wierszy
A = A.reshape(4,5)
print (A, '\n')
print (A[0], '\n')
print (A[1:], '\n')
print (A[:2], '\n')
print (A[: -1], '\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[0 1 2 3 4] 

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 



In [264]:
#Wycinanie kolumn
A = np.arange(20)
A = A.reshape(4, 5)
print (A, '\n')

print (A[:,1], '\n')
print (A[:,1:3], '\n')
print (A[:,:3], '\n')
print (A[:,-1], '\n')
print (A[:,:-1], '\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[ 1  6 11 16] 

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]] 

[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]] 

[ 4  9 14 19] 

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]] 



In [274]:
#wycinanie konkretnego elementu
print (A, '\n')
print (A[1,1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

6


In [279]:
#wycinanie konkretnego zakresu
print (A, '\n')
print (A[1:3,1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 6  7  8]
 [11 12 13]]


In [281]:
#przypisywanie wartości do macierzy
print (A, '\n')
A[1,3] = 16
print (A, '\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 0  1  2  3  4]
 [ 5  6  7 16  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 



**8.ITERACJA PO TABLICACH, ZMIANA ROZMIARU ORAZ MASKI LOGICZNE**

In [21]:
import numpy as np

A = np.arange(20)
A = A.reshape(4, 5)
print (A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
for row in A:
  print (row[3])

3
8
13
18


In [15]:
for item in A.flat:
  print (item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [25]:
for row in A[:,2:]:
  print (row)

[2 3 4]
[7 8 9]
[12 13 14]
[17 18 19]


**9.ZMIANA ROZMIARU TABLIC**

In [32]:
A
A.shape

A = A.reshape(5,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
#wypłaszczanie
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
#transponowanie
A.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

**10.MASKI LOGICZNE**

In [43]:
A = np.arange(-10, 10, 0.5)
A
A = A.reshape(10, -1)

In [44]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [46]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [48]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [50]:
A[np.bitwise_or(A>-5, A<5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])