<a href="https://colab.research.google.com/github/ChojnackiKRZ/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__
#print (dir(np))

1d array

In [ ]:
help(np.array)

In [11]:
x = np.array([1, 3])

In [ ]:
type (x)

In [ ]:
x.ndim

1

In [12]:
x.shape

(2,)

In [13]:
x.size

2

In [14]:
x.dtype

dtype('int64')

In [16]:
y = np.array([1.3, 2.4, 4.1])

In [17]:
y.dtype

dtype('float64')

2d array

In [20]:
z = np.array([[1, -3], [2, 6]])

In [21]:
z.ndim

2

In [22]:
z.shape

(2, 2)

In [24]:
x = np.array([[1, 2, 4],[3, 2, 1]])

In [25]:
x.shape

(2, 3)

3d array

In [34]:
x = np.array(
    [[[4, 3, 1],
      [2, 5, 1]],
     [[4, 3, 1],
      [4, 2, 1]],
     [[5, 6, 4],
      [9, 8, 2]]]
)

In [35]:
x.ndim

3

In [36]:
x.shape

(3, 2, 3)

PODSTAWOWE TYPY DANYCH

In [37]:
a = np.array([1.9, 2, 3])
a.dtype

dtype('float64')

In [39]:
a = np.array([1, 2, 3], dtype= 'float')
a

array([1., 2., 3.])

In [43]:
a = np.array([False, True])
a
a.dtype

dtype('bool')

In [61]:
#specjalne typy numpy
a = np.array([1, 28, 257], dtype = np.int8)
b = np.array([1, 28, 255], dtype = np.int8)
c = np.array([1, 28, 256], dtype = np.int8)
print (a, b, c)

[ 1 28  1] [ 1 28 -1] [ 1 28  0]


TWORZENIE TABLIC

In [ ]:
#help (np.zeros)
np.zeros((4,10))

In [73]:
np.zeros((4,10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [75]:
np.ones((5,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [77]:
np.full(shape = (3, 3), fill_value= 5, dtype = int)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [90]:
a = np.arange(1, 6, 2)
b = np.arange(1, 6, 2)
c = a + b
print (c)

[ 2  6 10]


In [100]:
np.arange(100, 49, -10)

array([100,  90,  80,  70,  60,  50])

In [ ]:
np.arange(0, 1, step = 0.01)

In [ ]:
for i in np.linspace(start = 0, stop = 1, num = 10):
  print (round (i, 1))

In [112]:
A = np.arange(15)

In [116]:
print (A)
A.reshape(5, 3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [123]:
#jeżeli nie chcesz liczyć, jaki ma być wymiar, podajesz jako pierwszy lub 
#drugi parametr -1
A = np.arange(20)
B = np.arange(15)
print (A.reshape(4, -1))
print (B.reshape(-1, 3))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
