<a href="https://colab.research.google.com/github/ChojnackiKRZ/data-science-bootcamp/blob/main/02_algebra_liniowa_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.NORMA WEKTORA, DŁUGOŚĆ WEKTORA W PRZESTRZENII R2**

In [ ]:
v1 = np.array([0, 4])
v1

np.linalg.norm(v1)

4.0

**2.NORMA EUKLIDESOWA W Rn**

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

**3.ODLEGŁOŚĆ DWÓCH PUNKTÓW NA PŁASZCZYŹNIE**

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

**4.ODLEGŁOŚĆ DWÓCH PUNKTÓW W PRZESTRZENII Rn**

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

**5.MNOŻENIE MACIERZY**

In [ ]:
x = np.array([[5, 3], [3, 9]])
y = np.array([[1], [-1]])

In [ ]:
z = np.dot(x, y)
z

array([[ 2],
       [-6]])

In [ ]:
X = np.array([[2, -1, 3], [3, 1, 0]])
Y = np.array([[2, 1, -1], [0, -1, 2], [3, 2, 0]])
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

**6.WYZNACZNIK MACIERZY**

In [3]:
import numpy as np
A = np.array([[2, 4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [5]:
#liczymy wyznacznik macierzy
round (np.linalg.det(A))

10

**7.ŚLAD MACIERZY**

Ślad macierzy: suma elementów na przekątnej

In [6]:
A = np.array([[2, 4], [-1, 3]])
A
#czyli dla tej macierzy mamy 5

array([[ 2,  4],
       [-1,  3]])

In [8]:
np.trace(A)

5

**8.MACIERZ JEDNOSTKOWA**

In [17]:
#macierz majaca same jedynki na przekatnej
np.eye(5, dtype = 'float')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**9.MACIERZ ODWROTNA**

In [21]:
A
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
#mnozenie macierzy dla sprawdzenia czy macierz B jest macierza odwrotna dla A

In [26]:
np.dot(A, B).round()

array([[1., 0.],
       [0., 1.]])

In [27]:
np.set_printoptions(precision = 4, suppress= True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [28]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

**10.MACIERZ TRANSPONOWANA**

In [30]:
#zamiana wierszy na kolumnę
A
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [31]:
A.T

array([[ 2, -1],
       [ 4,  3]])

**11.ROZWIĄZYWANIE UKŁADU RÓWNAŃ**

#równanie 
#         2x + 4y = 10
#         1x - 1y = -1

In [33]:
#macierz
A = np.array([[2, 4], [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [35]:
#wektor wyrazow wolnych
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [37]:
#macierz odwrotna dla A
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [38]:
#teraz należy przemnożyć macierz odwrotną przez wektor wyrazów wolnych
X = np.dot(A_inv, B)
X
#rozwiązaniem układu równań jest 1 i 2

array([[1.],
       [2.]])