<a href="https://colab.research.google.com/github/ChojnackiKRZ/data-science-bootcamp/blob/main/03_numpy_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**FUNKCJE STATYSTYCZNE**

In [2]:
import numpy as np
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000], 
                  [12.60, 12.40, 12.00, 12.90, 2000], 
                  [12.20, 12.90, 11.95, 13.00, 3000]])

In [5]:
#sum
price.sum(axis = 0)
price.sum(axis = 1)

array([  37.2 ,   38.1 ,   35.85,   38.5 , 6000.  ])

In [7]:
#min
price.min(axis = 0)
price.min(axis = 1)


array([11.9 , 12.  , 11.95])

In [8]:
#max
price.max(axis = 0)
price.max(axis = 1)

array([1000., 2000., 3000.])

In [13]:
#mediana
np.median(price)
np.median(price, axis = 0)
np.median(price, axis = 1)

array([12.6, 12.6, 12.9])

In [14]:
#średnia
np.mean(price)
np.mean(price, axis = 1)
np.mean(price, axis = 0)

array([  12.4       ,   12.7       ,   11.95      ,   12.83333333,
       2000.        ])

In [22]:
#odchylenie standardowe
np.set_printoptions(precision = 5, suppress = True)
np.std(price, axis = 0)

array([  0.1633 ,   0.21602,   0.04082,   0.16997, 816.49658])

In [23]:
#wariancja
np.var(price, axis = 0)

array([     0.02667,      0.04667,      0.00167,      0.02889,
       666666.66667])